export const DAYS_OF_WEEK = [
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
] as const;

export const DAY_MAP_JST: Record<string, number> = {
  sundays: 0,
  mondays: 1,
  tuesdays: 2,
  wednesdays: 3,
  thursdays: 4,
  fridays: 5,
  saturdays: 6,
  sunday: 0,
  monday: 1,
  tuesday: 2,
  wednesday: 3,
  thursday: 4,
  friday: 5,
  saturday: 6,
};

export const FALLBACK_AIRING_ANIME = [
  {
    mal_id: 21,
    title: "One Piece",
    title_english: "One Piece",
    image_url: "https://cdn.myanimelist.net/images/anime/1244/138851.jpg",
    airing: true,
    status: "Currently Airing",
    episodes_total: 0,
    episodes_watched_mal: 0,
    episodes_watched_local: 0,
    score: 8.72,
    broadcast: {
      day: "Sundays",
      time: "09:30",
      timezone: "Asia/Tokyo",
      string: "Sundays at 09:30 (JST)",
      sourceString: "Sundays at 09:30 (JST)",
    },
    synopsis:
      "Monkey D. Luffy sets out to locate the legendary 'One Piece' treasure and claim the title of King of the Pirates.",
    studio: "Toei Animation",
    trailer_url: "https://www.youtube.com/watch?v=l_9824n53I4",
    genres: [{ name: "Action" }, { name: "Adventure" }, { name: "Fantasy" }],
    season: "Ongoing",
    url: "https://myanimelist.net/anime/21/One_Piece",
  },
  {
    mal_id: 57335,
    title: "Oshi no Ko Season 2",
    title_english: "Oshi no Ko Season 2",
    image_url: "https://cdn.myanimelist.net/images/anime/1812/143521.jpg",
    airing: true,
    status: "Currently Airing",
    episodes_total: 13,
    episodes_watched_mal: 0,
    episodes_watched_local: 0,
    score: 8.62,
    broadcast: {
      day: "Wednesdays",
      time: "23:00",
      timezone: "Asia/Tokyo",
      string: "Wednesdays at 23:00 (JST)",
      sourceString: "Wednesdays at 23:00 (JST)",
    },
    synopsis:
      "The second season focuses on the Tokyo Blade Stage Play adaptation.",
    studio: "Doga Kobo",
    trailer_url: "https://www.youtube.com/watch?v=8p_h9q90b_c",
    genres: [{ name: "Drama" }, { name: "Supernatural" }],
    season: "Summer 2026",
    url: "https://myanimelist.net/anime/57335/Oshi_no_Ko_2nd_Season",
  },
];
